gitlab-ci: Move to previous buildah, freeze
What can break, will break!

New builah stable is broken:

```
Copying blob sha256:719701c1e06f1744038a9cbf7a0ebd1cec66aa405ed6c9fb7ff0500316be082c
517Copying blob sha256:e4220e24139af26c7436d277cf905e63eac4d046ea96873c84802d8fbd897a09
518Copying config sha256:b5c4cc409f822d966fe219edf79e5330cafba45ae5790d3b58ac1814bcdcb532
519Writing manifest to image destination
520Storing signatures
521time="2023-04-05T20:25:38Z" level=error msg="Unmounting /var/lib/containers/storage/overlay/adff8747ef3e52e87523114d4cc5ad6efd684c0a3d32ae6b489e5fd0c247c21c/merged: invalid argument"
522Error: mounting new container: mounting build container "b4ec3ef76f61eb51b56d1a6af9c937864495f972a6f0f0abe5233f2c5d770bc7": creating overlay mount to /var/lib/containers/storage/overlay/adff8747ef3e52e87523114d4cc5ad6efd684c0a3d32ae6b489e5fd0c247c21c/merged, mount_data="lowerdir=/var/lib/containers/storage/overlay/l/HGKMVDIOBXXR2QH2ATWHRAHZLQ:/var/lib/containers/storage/overlay/l/HZ3Q3NTIPEXH7TSXX5K426IQF7:/var/lib/containers/storage/overlay/l/JDHE3YCSKCXVZK7TA3LBBCW2GD:/var/lib/containers/storage/overlay/l/2BJ3XWKCAMDGC5T3SD3LK6G7VX:/var/lib/containers/storage/overlay/l/AST47X3BQPHLSO6SJ4HNR462HT:/var/lib/containers/storage/overlay/l/SHLJ27U7REC4DQEUR7Y74ZVE5G:/var/lib/containers/storage/overlay/l/FPMCZ6X4FVCZVU7ER35TIKQGAD:/var/lib/containers/storage/overlay/l/QCRJDWAOYGPH3ADMCALPCFED2Q:/var/lib/containers/storage/overlay/l/JRV2KNX3Z37H7UNL4RLY7TEJ2O:/var/lib/containers/storage/overlay/l/5IVOD2YU2LYC7CWCSXTMT6ZLGH:/var/lib/containers/storage/overlay/l/UUST36RJA5BMRFOIB2T7HQPFVC,upperdir=/var/lib/containers/storage/overlay/adff8747ef3e52e87523114d4cc5ad6efd684c0a3d32ae6b489e5fd0c247c21c/diff,workdir=/var/lib/containers/storage/overlay/adff8747ef3e52e87523114d4cc5ad6efd684c0a3d32ae6b489e5fd0c247c21c/work,nodev,fsync=0": invalid argument
523make: *** [Makefile:11: build] Error 125
```

Revert to previous working version

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>