testing-farm-request: Add `error` pipeline state
This pipeline state was missing. In certain corner cases it can happen that the error state is already
set, and the code can choke on it:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/gluetool/lib/python3.9/site-packages/gluetool_modules_framework/libs/threading.py", line 14, in run
    self.function(*self.args, **self.kwargs)
  File "/opt/gluetool/lib/python3.9/site-packages/gluetool_modules_framework/testing_farm/testing_farm_request.py", line 663, in handle_pipeline_cancellation
    pipeline_state = self.get_pipeline_state()
  File "/opt/gluetool/lib/python3.9/site-packages/gluetool_modules_framework/testing_farm/testing_farm_request.py", line 625, in get_pipeline_state
    return PipelineState(request['state'])
  File "/usr/lib64/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib64/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'error' is not a valid PipelineState
```

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>